# Generated by Django 2.1.7 on 2020-04-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KsModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KsModel.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('realName', models.CharField(max_length=20, null=True, verbose_name='realName')),
                ('starLevel', models.IntegerField(null=True, verbose_name=0)),
                ('mobileNo', models.IntegerField(null=True, verbose_name=11)),
                ('customType', models.IntegerField(null=True, verbose_name=0)),
                ('currency', models.IntegerField(null=True, verbose_name=0)),
                ('starName', models.CharField(max_length=30, null=True, verbose_name='starName')),
                ('customId', models.CharField(max_length=50, null=True, verbose_name='customId')),
            ],
        ),
    ]
